sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: zn010924
    url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?allowMultiQueries=true
  wechat:
    appid: wxed42889a0d196b87
    secret: 80c898e65cf442623be99ea71acf1a89

  redis:
    host: localhost
    port: 6379
    database: 10