spring:
    application:
      name: springboot-mybatis-quickstart
    datasource:
      url: jdbc:mysql://localhost:3306/web01
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: zn010924
mybatis:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

